In [5]:
import torch
import numpy as np 
import pandas as pd 
from transformers import BertTokenizer, BertModel, BertForMaskedLM, AutoTokenizer, AutoModelForMaskedLM
from scipy.spatial.distance import cosine 
import tokenizers 
import pandas as pd 
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score
from nltk.corpus import stopwords
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
# import snowballstemmer
import numpy
import os 
import re
import json
import pickle 

In [6]:
# vocab_path = os.getcwd()+'/bert_model/vocab_low_data.txt'
# model_path = os.getcwd()+'/blabla/'

In [7]:
# vocab_path

In [8]:
# tokenizers = BertTokenizer.from_pretrained(vocab_path)
# model = BertForMaskedLM.from_pretrained(pretrained_model_name_or_path=model_path, return_dict = True, output_hidden_states = True)

In [9]:
model = AutoModelForMaskedLM.from_pretrained("Shushant/nepaliBERT", output_hidden_states = True, return_dict = True, output_attentions = True)

In [10]:
tokenizers = AutoTokenizer.from_pretrained("Shushant/nepaliBERT")

In [11]:
# pickle.dump(model, open('bert_embeddings','wb'))

In [12]:
# pickle.dump(tokenizers, open('bert_tokenizers','wb'))

model = pickle.load(open('bert_embeddings','rb'))
tokenizers= pickle.load(open('bert_tokenizers','rb'))

In [16]:
tokenizers.tokenize("के मौजुदा लोकतान्त्रिक व्यवस्था राज्य पुनःसंरचनासँग जोडिएका हिजोका सवालहरूलाई यथास्थितिमा छोडेर सबल होला?")

['क',
 'मौ',
 '##ज',
 '##दा',
 'लोक',
 '##तान',
 '##तर',
 '##िक',
 'वय',
 '##वस',
 '##था',
 'राज',
 '##य',
 'पन',
 '##ः',
 '##सर',
 '##चना',
 '##सग',
 'जोडिएका',
 'हिजोका',
 'सवाल',
 '##हर',
 '##लाई',
 'यथा',
 '##स',
 '##थिति',
 '##मा',
 'छोड',
 '##र',
 'सबल',
 'होला',
 '?']

In [ ]:
# text = 'अनि तेस्रो चिन्ता मौसम परिवर्तनले हिमशिखरहरूमा परेका आघातसँगसँगै सिमानावारिपारि नदीले ल्याएका प्रकोपहरू कसरी सम्हाल्ने'
# marked_text = " [CLS] "+text+" [SEP] "
# tokenized_text = tokenizer.tokenize(marked_text)
# indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)
# segments_ids = [1] * len(indexed_tokens)

# tokens_tensors = torch.tensor([indexed_tokens])
# segments_tensors = torch.tensor([segments_ids])

In [ ]:
# with torch.no_grad():
#     outputs = model(tokens_tensors, segments_tensors)
#     hidden_states = outputs.hidden_states
# #     print(hidden_states[-1])
#     token_embeddings = hidden_states[-1]
    
#     token_embeddings = torch.squeeze(token_embeddings, dim = 0)
    
#     list_token_embeddings = [token_embed.tolist() for token_embed in token_embeddings]
#     print(list_token_embeddings)

In [ ]:
# nepali_stemmer = snowballstemmer.NepaliStemmer()

In [ ]:
# texts = ['तर','दुधमा तर बसेन|','तिम्रो घर आउन मन लाग्छ तर अल्छि लाग्छ']

In [ ]:
# def bert_text_preparation(text, tokenizer ):
#     """Preparing input for BERT"""
    
#     marked_text = " [CLS] " + text + " [SEP] "
#     tokenized_text = tokenizer.tokenize(marked_text)
#     indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)
#     segments_ids = [1] * len(indexed_tokens) 
    
#     # Convert inputs to Pytorch tensors
#     tokens_tensors = torch.tensor([indexed_tokens])
#     segments_tensors = torch.tensor([segments_ids])
    
#     return tokenized_text, tokens_tensors, segments_tensors

In [14]:
# def get_bert_embeddings(tokens_tensor, segments_tensors, model):
#     # Gradient claculation id disabled 
#     # Model is in inference mode
    
#     with torch.no_grad():
#         outputs = model(tokens_tensor, segments_tensors)
#         # removing the first hidden state
#         # the first state is the input state 
#         hidden_states = outputs.hidden_states
    
#     # Getting embeddings from final Bert Layer
#     tokens_embeddings = hidden_states[-1]
#     # Collasping the tensor into 1-dimension 
#     tokens_embeddings = torch.squeeze(tokens_embeddings, dim = 0)
#     # Converting torchtensors to lists 
#     list_token_embeddings = [token_embed.tolist() for token_embed in tokens_embeddings]
    
#     return list_token_embeddings 

In [15]:
# tokenized_text, tokens_tensors, segments_tensors = bert_text_preparation(text, tokenizer)
# target_word_embeddings = []

# for text in texts:
#     tokenized_text, tokens_tensors, segments_tensors = bert_text_preparation(text, tokenizer)
#     list_token_embeddings = get_bert_embeddings(tokens_tensors, segments_tensors, model)
#     ## list_token_embeddings has embeddings of the given words
# #     word_index = tokenized_text.index('तर')
#     word_embeddings = [list_token_embeddings[token] for token in tokenized_text]
# #     word_embedding = list_token_embeddings[word_index]
# #     print(word_embedding)
# #     target_word_embeddings.append(word_embedding)

In [19]:
# tokenized_text

In [20]:
# type(tokenized_text[0])

In [21]:
# target_word_embeddings = []

# for text in texts:
#     tokenized_text, tokens_tensors, segments_tensors = bert_text_preparation(text, tokenizers)
#     list_token_embeddings = get_bert_embeddings(tokens_tensors, segments_tensors, model)
# #     print(len(list_token_embeddings))
#     ## list_token_embeddings has embeddings of the given words
#     word_index = tokenized_text.index('तर')
#     word_embedding = list_token_embeddings[word_index]
# #     print(word_embedding)
#     target_word_embeddings.append(word_embedding)

In [22]:
# target_word_embeddings[0] == target_word_embeddings[1]

In [26]:
# len(target_word_embeddings)

In [24]:
# list_of_distances = []
# for text1, embed1 in zip(texts, target_word_embeddings):
#     for text2, embed2 in zip(texts, target_word_embeddings):
#         cos_dist = 1 - cosine(embed1,embed2)
#         list_of_distances.append([text1, text2, cos_dist])


# distances_df = pd.DataFrame(list_of_distances, columns = ['text1','text2','distance'])


In [1]:
# df = pd.read_csv("finalData.csv")
import pandas as pd
df = pd.read_csv('collected_labeled_data.csv')

In [2]:
df['label'].unique()

array([2, 1, 0])

In [19]:
# df.to_csv('collected_labeled_data.csv',index = False)

In [6]:
neutral_df = df[df.label==2]

In [8]:
neutral_df.to_csv("neutral.csv")

In [20]:
# train_X, test_X = train_test_split(df, test_size = 0.2)

In [21]:
# train_X.to_csv('train.csv',index = False)
# test_X.to_csv('test.csv',index = False)

In [22]:
# def check_len(text):
#     txt = text.split(' ')[:20]
#     return ' '.join(txt)

In [23]:
# df['text'] = df['text'].apply(check_len)

In [24]:
# def get_word_embeddings(text):
#     tokenizer = tokenizers
#     tokenized_text, tokens_tensors, segments_tensors = bert_text_preparation(text, tokenizer)
#     list_token_embeddings = get_bert_embeddings(tokens_tensors, segments_tensors, model)
#     ## list_token_embeddings has embeddings of the given words
#     return list_token_embeddings

In [25]:
# stopwords= stopwords.words("nepali")

In [26]:
# words = ['अक्सर','आदि','कसरी','अन्तर्गत','अर्थात','अर्थात्','अलग','आयो','उदाहरण','एकदम','राम्रो','बिरुद्ध','बिशेष','नराम्रो']

In [27]:
# stopwords = list(set(stopwords).difference(set(words)))

In [28]:
# def remove_emojis(text):
#     emoji_pattern = re.compile("["
#         u"\U0001F600-\U0001F64F"  # emoticons
#         u"\U0001F300-\U0001F5FF"  # symbols & pictographs
#         u"\U0001F680-\U0001F6FF"  # transport & map symbols
#         u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
#         u"\U00002500-\U00002BEF"  # chinese char
#         u"\U00002702-\U000027B0"
#         u"\U00002702-\U000027B0"
#         u"\U000024C2-\U0001F251"
#         u"\U0001f926-\U0001f937"
#         u"\U00010000-\U0010ffff"
#         u"\u2640-\u2642" 
#         u"\u2600-\u2B55"
#         u"\u200d"
#         u"\u23cf"
#         u"\u23e9"
#         u"\u231a"
#         u"\ufe0f" # dingbats
#         u"\u3030"
#     "]+", re.UNICODE)
#     text = emoji_pattern.sub(r'', text)
#     return text

In [29]:
# def clean_text(text):
#     text = remove_emojis(text)
# #     text = text.split(' ')
# #     clean_text_list = []
# #     for word in text:
# #         if word not in stopwords:
# #             clean_text_list.append(word)
# #     clean_text = ' '.join(clean_text_list)
# #     stem_words = nepali_stemmer.stemWords(text.split())
# #     stem_text = ' '.join(stem_words)
# #     txt = re.sub(r"[|a-zA-z.'#0-9@,:?'\u200b\u200c\u200d!/&~-]",'',text)
#     return text

In [30]:
# clean_text("घाम जति लग्यो हामीलाई तेती राम्रो हुन्छ apple ")

In [31]:
# df['text'] = df['text'].apply(clean_text)


In [32]:
df.head()

text  label
0  बजार ले जसरी ट्रेन्ड चेन्ज गर्यो यो हेर्दा तत्...      2
1  1000 अंकले घटेको नेप्से 200 अंकले बढ्नु ठूलो क...      1
2  होइन यो सानिमा बैंक ले bonus घोसणा गरेको २ महि...      2
3  खैँ MBJC प्रति कित्तामा रू,10/-ले बढेर आज रू,1...      2
4                                       राम्रो भयो️️      1

In [33]:
def get_bert_embedding_sentence(input_sentence):
#     md = model
#     tokenizer = tokenizers
    md = local_model
    tokenizer = local_tokenizers
    marked_text = " [CLS] " + input_sentence + " [SEP] "
    tokenized_text = tokenizer.tokenize(marked_text)

    indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)
    segments_ids = [1] * len(indexed_tokens) 
    
    # Convert inputs to Pytorch tensors
    tokens_tensors = torch.tensor([indexed_tokens])
    segments_tensors = torch.tensor([segments_ids])
    
    with torch.no_grad():
        outputs = md(tokens_tensors, segments_tensors)
        # removing the first hidden state
        # the first state is the input state 

        hidden_states = outputs.hidden_states
#         print(hidden_states[-2])
        # second_hidden_states = outputs[2]
    # hidden_states has shape [13 x 1 x 22 x 768]

    # token_vecs is a tensor with shape [22 x 768]
#     token_vecs = hidden_states[-2][0]
    # get last four layers
#     last_four_layers = [hidden_states[i] for i in (-1,-2, -3,-4)]


    # cast layers to a tuple and concatenate over the last dimension
#     cat_hidden_states = torch.cat(tuple(last_four_layers), dim=-1)
#     print(cat_hidden_states.shape)
    token_vecs = hidden_states[-2][0]

    # take the mean of the concatenated vector over the token dimension
#     sentence_embedding = torch.mean(cat_hidden_states, dim=0).squeeze()

    # Calculate the average of all 22 token vectors.
    sentence_embedding = torch.mean(token_vecs, dim=0)
#     sentence_embedding = torch.mean(token_vecs, dim=1)
    return sentence_embedding.numpy()

In [34]:
# get_bert_embedding_sentence("नेपाल को ससकृती ध्वस्त पार्ने योजना")

In [35]:
df=df.drop(df[df['label']==2].index)

In [36]:
df.dropna(inplace = True)

In [37]:
df['word_embeddings'] = df['text'].apply(get_bert_embedding_sentence)

NameError: name 'local_model' is not defined

In [48]:
df.shape

(6056, 3)

In [49]:
df.head()

text  label  \
1   1000 अंकले घटेको नेप्से 200 अंकले बढ्नु ठूलो क...      1   
4                                        राम्रो भयो️️      1   
6                 जानकारीको लागि धन्यवाद रामहरी ब्रदर      1   
18  भारत-मधेस र नेपाल-चीन सम्बन्ध विग्रन्छ, मधेसी ...      0   
25  लेखनाथ न्यौपानेको खुलासा,महाधिबेशनमा एमसीसीको ...      0   

                                      word_embeddings  
1   [-0.26195702, 0.53875995, -0.16427916, 0.25294...  
4   [-0.30638546, 0.9532779, -0.38146943, 0.543288...  
6   [0.3177412, 0.658264, -0.12128312, 0.06808513,...  
18  [0.15587394, 0.6471651, -0.13978052, -0.099823...  
25  [-0.1403608, 0.88074046, 0.0538228, 0.11658574...

In [50]:
# df.to_csv('embedding_data.csv',index = False)

In [51]:
X,y = df['word_embeddings'], df['label']

In [52]:
# scaler = StandardScaler()
# pca = PCA(n_components = 768)

In [53]:
# scaled_X = scaler.fit_transform(X.tolist())
# pca_X = pca.fit_transform(scaled_X)

In [54]:
train_X, test_X, train_y, test_y = train_test_split(X,y, test_size = 0.2, random_state = 420)

In [55]:
SVC??

In [56]:
svc = SVC(probability=True)

In [57]:
# train_X = [i[0] for i in train_X]
# test_X = [i[0] for i in test_X]

In [58]:
# train_X[0][0].shape

In [59]:
svc.fit(train_X.tolist(), train_y)
#svc.fit(train_X, train_y)

SVC(probability=True)

In [60]:
svc_pred = svc.predict(test_X.tolist())
# svc_pred = svc.predict(test_X)

In [61]:
print(confusion_matrix(test_y, svc_pred))

[[429  86]
 [ 67 630]]


In [62]:
print(classification_report(test_y, svc_pred))

              precision    recall  f1-score   support

           0       0.86      0.83      0.85       515
           1       0.88      0.90      0.89       697

    accuracy                           0.87      1212
   macro avg       0.87      0.87      0.87      1212
weighted avg       0.87      0.87      0.87      1212



In [63]:
accuracy_score(test_y, svc_pred)

0.8737623762376238

In [64]:
f1_score(test_y, svc_pred)

0.89171974522293

In [65]:
sent = "नराम्रो"
predicted_label = svc.predict_proba(np.array(get_bert_embedding_sentence(sent).tolist()).reshape(1,-1))[0]
if predicted_label[0]<predicted_label[1]:
    print(f'{sent} is negative sentiment')
else:
    print(f'{sent} is positive sentiment')

नराम्रो is negative sentiment


In [66]:
pickle.dump(svc, open('scv_sentiment','wb'))

In [67]:

# pickle.dump(svc,open('svc_sentiment','wb'))

In [68]:
svc_sentiment = pickle.load(open('svc_sentiment','rb'))

/home/info/.local/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator SVC from version 1.0.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(


In [69]:
predicted_label

array([0.46629947, 0.53370053])