In [42]:
import pandas as pd

In [43]:
data = pd.read_csv("covid19_tweeter_dataset.csv")

In [44]:
data

Unnamed: 0  Label                   Datetime  \
0               0     -1  2021-01-10 22:06:41+00:00   
1               1     -1  2021-01-10 17:49:34+00:00   
2               2      1  2021-01-10 16:18:34+00:00   
3               3      0  2021-01-10 15:12:17+00:00   
4               4     -1  2021-01-10 15:07:12+00:00   
...           ...    ...                        ...   
33469       33469      0  2020-02-12 01:33:08+00:00   
33470       33470      0  2020-02-12 00:38:07+00:00   
33471       33471      0  2020-02-11 19:37:26+00:00   
33472       33472      0  2020-02-11 16:36:40+00:00   
33473       33473      0  2020-02-11 15:22:16+00:00   

                                                   Tweet  \
0      अमेरिकामा कोभिड बाट एकै दिन चार हजारभन्दा बढीक...   
1      कोभिड का कारण विदेशमा रहेका नेपालीहरुमा मानसिक...   
2      नेपालमा क्लोभर बायोफार्मास्युटिकल्स अस्ट्रेलिय...   
3                                कोभिड को खोप पनि लगाइयो   
4      अमेरिकामा कोभिड को नयाँ रेकर्ड एकै दिन हजारभन्...   
...                                                  ...   
33469  कोरोना भाइरसलाई विश्व स्वास्थ्य संगठनले दियो न...   
33470       डब्ल्युएचओले दियाेको कोरोनाको नयाँ नाम कोभिड   
33471        कोरोना भाइरस संक्रमणको औपचारिक नाम अब कोभिड   
33472  विश्व स्वास्थ्य संगठन डब्लुएचओ ले नोबल कोरोना ...   
33473  कोरोनाभाइरसका सङ्क्रमणको नाम कोभिड भनेर विश्व ...   

                                          Tokanize_tweet Unnamed: 5  
0      अमेरिकामा,कोभिड,बाट,एकै,दिन,चार,हजारभन्दा,बढीक...        NaN  
1      कोभिड,का,कारण,विदेशमा,रहेका,नेपालीहरुमा,मानसिक...        NaN  
2      नेपालमा,क्लोभर,बायोफार्मास्युटिकल्स,अस्ट्रेलिय...        NaN  
3                                कोभिड,को,खोप,पनि,लगाइयो        NaN  
4      अमेरिकामा,कोभिड,को,नयाँ,रेकर्ड,एकै,दिन,हजारभन्...        NaN  
...                                                  ...        ...  
33469  कोरोना,भाइरसलाई,विश्व,स्वास्थ्य,संगठनले,नाम,कोभिड        NaN  
33470            डब्ल्युएचओले,दियाेको,कोरोनाको,नाम,कोभिड        NaN  
33471           कोरोना,भाइरस,संक्रमणको,औपचारिक,नाम,कोभिड        NaN  
33472  विश्व,स्वास्थ्य,संगठन,डब्लुएचओ,नोबल,कोरोना,भाइ...        NaN  
33473  कोरोनाभाइरसका,सङ्क्रमणको,नाम,कोभिड,विश्व,स्वास...        NaN  

[33474 rows x 6 columns]

In [45]:
data['Tweet'][30]

'प्रधानमँत्रीज्यू चुनाव गर्ने पैसा हुने तर कोभीड बाट जनताको लागि निशूल्क खोप ल्याउन पैसा नहुने खोप ल्याउन किन ढिलाइ गरिँदैछ देश र जनताप्रति किन लापरबाही'

In [46]:
data['length'] = data['Tokanize_tweet'].apply(
    lambda row: min(len(row.split(",")), len(row)) if isinstance(row, str) else None
)

In [47]:
max(data['length'].tolist())

61.0

In [48]:
data["Tweet"][1]

'कोभिड का कारण विदेशमा रहेका नेपालीहरुमा मानसिक स्वास्थ्य सम्बन्धि समस्या देखिएको र आत्महत्याका घटनाहरु बढेको डा सापकोटाले बताए'

In [49]:
data.head()

Unnamed: 0  Label                   Datetime  \
0           0     -1  2021-01-10 22:06:41+00:00   
1           1     -1  2021-01-10 17:49:34+00:00   
2           2      1  2021-01-10 16:18:34+00:00   
3           3      0  2021-01-10 15:12:17+00:00   
4           4     -1  2021-01-10 15:07:12+00:00   

                                               Tweet  \
0  अमेरिकामा कोभिड बाट एकै दिन चार हजारभन्दा बढीक...   
1  कोभिड का कारण विदेशमा रहेका नेपालीहरुमा मानसिक...   
2  नेपालमा क्लोभर बायोफार्मास्युटिकल्स अस्ट्रेलिय...   
3                            कोभिड को खोप पनि लगाइयो   
4  अमेरिकामा कोभिड को नयाँ रेकर्ड एकै दिन हजारभन्...   

                                      Tokanize_tweet Unnamed: 5  length  
0  अमेरिकामा,कोभिड,बाट,एकै,दिन,चार,हजारभन्दा,बढीक...        NaN     9.0  
1  कोभिड,का,कारण,विदेशमा,रहेका,नेपालीहरुमा,मानसिक...        NaN    18.0  
2  नेपालमा,क्लोभर,बायोफार्मास्युटिकल्स,अस्ट्रेलिय...        NaN    20.0  
3                            कोभिड,को,खोप,पनि,लगाइयो        NaN     5.0  
4  अमेरिकामा,कोभिड,को,नयाँ,रेकर्ड,एकै,दिन,हजारभन्...        NaN    12.0

In [50]:
data["Tokanize_tweet"][1]

'कोभिड,का,कारण,विदेशमा,रहेका,नेपालीहरुमा,मानसिक,स्वास्थ्य,सम्बन्धि,समस्या,देखिएको,र,आत्महत्याका,घटनाहरु,बढेको,डा,सापकोटाले,बताए'

In [51]:
data["Label"].value_counts()

 1    14998
-1    13606
 0     4870
Name: Label, dtype: int64

In [52]:
import torch
import numpy as np 
import pandas as pd 
from transformers import BertTokenizer, BertModel, BertForMaskedLM, AutoTokenizer, AutoModelForMaskedLM
from scipy.spatial.distance import cosine 
import tokenizers 
import pandas as pd 
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score
from nltk.corpus import stopwords
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
# import snowballstemmer
import numpy
import os 
import re
import json
import pickle 

In [53]:
model = AutoModelForMaskedLM.from_pretrained("Shushant/nepaliBERT", output_hidden_states = True, return_dict = True, output_attentions = True)

loading configuration file https://huggingface.co/Shushant/nepaliBERT/resolve/main/config.json from cache at /home/fm-pc-lt-228/.cache/huggingface/transformers/c642996ea6b3b6351e3519c0b5059b07a6b8a1a8e4961bf81d181326b75cabfe.3abddfe906646a59813d34e11ed576b8ddb2023553640fa3ce71f000d3c234d0
Model config BertConfig {
  "_name_or_path": "Shushant/nepaliBERT",
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "output_attentions": true,
  "output_hidden_states": true,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "torch_dtype": "float32",
  "transformers_version": "4.15.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30

In [54]:
tokenizers = AutoTokenizer.from_pretrained("Shushant/nepaliBERT")

Could not locate the tokenizer configuration file, will try to use the model config instead.
loading configuration file https://huggingface.co/Shushant/nepaliBERT/resolve/main/config.json from cache at /home/fm-pc-lt-228/.cache/huggingface/transformers/c642996ea6b3b6351e3519c0b5059b07a6b8a1a8e4961bf81d181326b75cabfe.3abddfe906646a59813d34e11ed576b8ddb2023553640fa3ce71f000d3c234d0
Model config BertConfig {
  "_name_or_path": "Shushant/nepaliBERT",
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "torch_dtype": "float32",
  "transformers_version": "4.15.0",
  "type_vocab_size": 2,
  "use_

In [55]:
pickle.dump(model, open('bert_embeddings','wb'))

In [56]:
pickle.dump(tokenizers, open('bert_tokenizers','wb'))

In [57]:
model = pickle.load(open('bert_embeddings','rb'))
tokenizers= pickle.load(open('bert_tokenizers','rb'))

In [58]:
tokenizers.tokenize("के मौजुदा लोकतान्त्रिक व्यवस्था राज्य पुनःसंरचनासँग जोडिएका हिजोका सवालहरूलाई यथास्थितिमा छोडेर सबल होला?")

['क',
 'मौ',
 '##ज',
 '##दा',
 'लोक',
 '##तान',
 '##तर',
 '##िक',
 'वय',
 '##वस',
 '##था',
 'राज',
 '##य',
 'पन',
 '##ः',
 '##सर',
 '##चना',
 '##सग',
 'जोडिएका',
 'हिजोका',
 'सवाल',
 '##हर',
 '##लाई',
 'यथा',
 '##स',
 '##थिति',
 '##मा',
 'छोड',
 '##र',
 'सबल',
 'होला',
 '?']

In [59]:
def get_bert_embedding_sentence(input_sentence):
    md = model
    tokenizer = tokenizers
#     md = local_model
#     tokenizer = local_tokenizers
    marked_text = " [CLS] " + input_sentence + " [SEP] "
    tokenized_text = tokenizer.tokenize(marked_text)

    indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)
    segments_ids = [1] * len(indexed_tokens) 
    
    # Convert inputs to Pytorch tensors
    tokens_tensors = torch.tensor([indexed_tokens])
    segments_tensors = torch.tensor([segments_ids])
    
    with torch.no_grad():
        outputs = md(tokens_tensors, segments_tensors)
        # removing the first hidden state
        # the first state is the input state 

        hidden_states = outputs.hidden_states
#         print(hidden_states[-2])
        # second_hidden_states = outputs[2]
    # hidden_states has shape [13 x 1 x 22 x 768]

    # token_vecs is a tensor with shape [22 x 768]
#     token_vecs = hidden_states[-2][0]
    # get last four layers
#     last_four_layers = [hidden_states[i] for i in (-1,-2, -3,-4)]
    # cast layers to a tuple and concatenate over the last dimension
#     cat_hidden_states = torch.cat(tuple(last_four_layers), dim=-1)
#     print(cat_hidden_states.shape)
    token_vecs = hidden_states[-2][0]
    # take the mean of the concatenated vector over the token dimension
#     sentence_embedding = torch.mean(cat_hidden_states, dim=0).squeeze()

    # Calculate the average of all 22 token vectors.
    sentence_embedding = torch.mean(token_vecs, dim=0)
#     sentence_embedding = torch.mean(token_vecs, dim=1)
    return sentence_embedding.numpy()

In [60]:
data['word_embeddings'] = data['Tweet'].apply(get_bert_embedding_sentence)

In [61]:
X,y = data['word_embeddings'], data['Label']

In [62]:
train_X, test_X, train_y, test_y = train_test_split(X,y, test_size = 0.2, random_state = 420)

train_df,test_df = train_test_split(data, test_size = 0.2, random_state = 420)

train_df.to_csv("train.csv")

test_df.to_csv("test.csv")

In [34]:
svc = SVC(probability=True)

In [35]:
svc.fit(train_X.tolist(), train_y)
#svc.fit(train_X, train_y)

SVC(probability=True)

In [42]:
svc_pred = svc.predict(test_X.tolist())
# svc_pred = svc.predict(test_X)

In [37]:
print(confusion_matrix(test_y, svc_pred))

[[2258   49  449]
 [ 312  188  484]
 [ 505   48 2402]]


In [38]:
print(classification_report(test_y, svc_pred))

              precision    recall  f1-score   support

          -1       0.73      0.82      0.77      2756
           0       0.66      0.19      0.30       984
           1       0.72      0.81      0.76      2955

    accuracy                           0.72      6695
   macro avg       0.70      0.61      0.61      6695
weighted avg       0.72      0.72      0.70      6695



In [39]:
accuracy_score(test_y, svc_pred)

0.7241224794622853

In [41]:
sent = "नराम्रो"
predicted_label = svc.predict_proba(np.array(get_bert_embedding_sentence(sent).tolist()).reshape(1,-1))[0]
if predicted_label[0]<predicted_label[1]:
    print(f'{sent} is negative sentiment')
else:
    print(f'{sent} is positive sentiment')

नराम्रो is negative sentiment


In [64]:
from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,
    max_depth=1, random_state=0).fit(train_X.tolist(), train_y)
gbc.score(test_X.tolist(), test_y)

0.6766243465272591

In [65]:

from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0).fit(train_X.tolist(), train_y)



clf.score(test_X.tolist(), test_y)

/home/fm-pc-lt-228/anaconda3/envs/nepali/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.7047050037341299

In [66]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(train_X.tolist(), train_y)
gnb.score(test_X.tolist(), test_y)

0.5870052277819268

In [67]:
gnb_pred = gnb.predict(test_X.tolist())
print(confusion_matrix(test_y, gnb_pred))

[[1491  599  666]
 [ 124  473  387]
 [ 336  653 1966]]


## Deep Learning

In [72]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.models import Model
from keras.layers import LSTM, Activation, Dense, Dropout, Input, Embedding
from keras.optimizers import RMSprop
from keras.preprocessing.text import Tokenizer
from keras.preprocessing import sequence
from keras.utils import to_categorical
from keras.callbacks import EarlyStopping
%matplotlib inline

## Finetuning with NepBERT

In [16]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained("Shushant/nepaliBERT", num_labels=3)

Some weights of the model checkpoint at Shushant/nepaliBERT were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at Shushant/nepaliBERT and a

In [17]:
import numpy as np
import evaluate

metric = evaluate.load("accuracy")

2022-09-17 22:53:52.854163: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-09-17 22:53:52.878462: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-09-17 22:53:52.878476: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [18]:
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

In [19]:
from datasets import load_dataset

dataset = load_dataset("Shushant/CovidNepaliTweets")
dataset["train"][100]

Using custom data configuration Shushant--CovidNepaliTweets-00a71fabf99a7743
Reusing dataset csv (/home/fm-pc-lt-228/.cache/huggingface/datasets/Shushant___csv/Shushant--CovidNepaliTweets-00a71fabf99a7743/0.0.0/652c3096f041ee27b04d2232d41f10547a8fecda3e284a79a0ec4053c916ef7a)


  0%|          | 0/2 [00:00<?, ?it/s]

{'Label': 0,
 'Text': 'नेपाली कांग्रेसका वरिष्ठनेता अादरणिय श्री रामचन्द्र पौडेलज्यूको प्रमुख अातिथ्यतामा कोभिड पछिको विश्वसन्दर्भमा लोकतान्त्रिक समाजबादको सान्दर्भिकता विषयक प्रदेश स्तरिय जुम मिटिङ्ग फेसबुकमा गते जेष्ठ बुधबार बजे लाईभ गरिनेछ सामाजिक लोकतन्त्र अध्ययन केन्द्र'}

In [28]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("Shushant/nepaliBERT")

max_length = 61
def tokenize_function(examples):
    return tokenizer(examples['Text'], padding='max_length', truncation=True, max_length=max_length)


tokenized_datasets = dataset.map(tokenize_function, batched=True)

Could not locate the tokenizer configuration file, will try to use the model config instead.
loading configuration file https://huggingface.co/Shushant/nepaliBERT/resolve/main/config.json from cache at /home/fm-pc-lt-228/.cache/huggingface/transformers/c642996ea6b3b6351e3519c0b5059b07a6b8a1a8e4961bf81d181326b75cabfe.3abddfe906646a59813d34e11ed576b8ddb2023553640fa3ce71f000d3c234d0
Model config BertConfig {
  "_name_or_path": "Shushant/nepaliBERT",
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "torch_dtype": "float32",
  "transformers_version": "4.15.0",
  "type_vocab_size": 2,
  "use_

  0%|          | 0/27 [00:00<?, ?ba/s]

  0%|          | 0/7 [00:00<?, ?ba/s]

In [29]:
tokenized_datasets['train'][0]

{'Label': 1,
 'Text': 'आचार्य जी हर बिमारी का इलाज ढुढलेते हैं आप अब तक कोभीड का कोइ इलाज वा दवा क्यों नहिं खोज पाए हैं',
 'input_ids': [2,
  8575,
  1022,
  2260,
  2699,
  7590,
  1714,
  1701,
  9525,
  1037,
  380,
  1061,
  4102,
  402,
  4167,
  2227,
  30176,
  1805,
  4690,
  1051,
  1701,
  3615,
  9525,
  1037,
  1862,
  8773,
  367,
  1700,
  11992,
  1027,
  2426,
  4583,
  402,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'token_type_ids': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'attention_mask': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1

In [30]:
len(tokenized_datasets['train'][0]['attention_mask'])

61

In [35]:
small_train_dataset = tokenized_datasets["train"].shuffle(seed=42).select(range(1000))
small_eval_dataset = tokenized_datasets["test"].shuffle(seed=42).select(range(1000))

In [36]:
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(output_dir="test_trainer", evaluation_strategy="epoch")

PyTorch: setting up devices
The default value for the training argument `--report_to` will change in v5 (from all installed integrations to none). In v5, you will need to use `--report_to all` to get the same behavior as now. You should start updating your code and make this info disappear :-).


In [37]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=small_train_dataset,
    eval_dataset=small_eval_dataset,
    compute_metrics=compute_metrics,
)

In [38]:
trainer.train()

The following columns in the training set  don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: Label, Text.
***** Running training *****
  Num examples = 1000
  Num Epochs = 3
  Instantaneous batch size per device = 8
  Total train batch size (w. parallel, distributed & accumulation) = 8
  Gradient Accumulation steps = 1
  Total optimization steps = 375


RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.